# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='rua')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='complemento')),
                ('number', models.PositiveIntegerField(verbose_name='numero')),
                ('district', models.CharField(max_length=255, verbose_name='bairro')),
                ('city', models.CharField(max_length=255, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'ACRE'), ('AL', 'ALAGOAS'), ('AM', 'AMAZONAS'), ('AP', 'AMAPÁ'), ('BA', 'BAHIA'), ('CE', 'CEARÁ'), ('DF', 'BRASÍLIA'), ('ES', 'ESPÍRITO SANTO'), ('GO', 'GOIÁS'), ('MA', 'MARANHÃO'), ('MG', 'MINAS GERAIS'), ('MS', 'MATO GROSSO DO SUL'), ('MT', 'MATO GROSSO'), ('PA', 'PARÁ'), ('PB', 'PARAÍBA'), ('PE', 'PERNAMBUCO'), ('PI', 'PIAUÍ'), ('PR', 'PARANÁ'), ('RJ', 'RIO DE JANEIRO'), ('RN', 'RIO GRANDE DO NORTE'), ('RO', 'RONDÔNIA'), ('RR', 'RORAIMA'), ('RS', 'RIO GRANDE DO SUL'), ('SC', 'SANTA CATARINA'), ('SE', 'SERGIPE'), ('SP', 'SÃO PAULO'), ('TO', 'TOCANTINS')], max_length=2, verbose_name='estado')),
                ('zipcode', models.CharField(max_length=10, verbose_name='CEP')),
                ('is_supplier', models.BooleanField(verbose_name='fornecedor')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('fancy_name', models.CharField(max_length=255, verbose_name='nome fantasia/apelido')),
                ('document', models.CharField(max_length=18, null=True, unique=True, verbose_name='CNPJ/CPF')),
                ('phone', models.CharField(blank=True, max_length=18, null=True, verbose_name='telefone')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': 'cliente/fornecedor',
                'verbose_name_plural': 'clientes/fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive', models.BooleanField(verbose_name='inativo')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('bar_code', models.CharField(max_length=30, null=True, unique=True, verbose_name='código de barra')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='preço')),
                ('ncm', models.CharField(max_length=20, verbose_name='NCM')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criando em')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['name'],
            },
        ),
    ]
