# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='fancy_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nome fantasia/apelido'),
        ),
    ]
