# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-21 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160505_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Pagamento')),
                ('additions', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Acrésimos')),
            ],
            options={
                'verbose_name_plural': 'formas de pagamentos',
                'verbose_name': 'Forma de Pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Person', verbose_name='Cliente')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name_plural': 'vendas',
                'verbose_name': 'venda',
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Preço')),
            ],
            options={
                'verbose_name_plural': 'Itens venda',
                'verbose_name': 'Item venda',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.CharField(max_length=10, verbose_name='NCM'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product', verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_dat', to='core.Sale'),
        ),
    ]
